global_costmap:

  global_frame: /map    # the coordinate frame the costmap should run in
  static_map: true    #determines whether or not the costmap should initialize itself based on a map
  rolling_window: false


 


  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}



