joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

front_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: Wheel_LHS_Front_Joint
  pid:
    p: 100.0
    i: 0.1
    d: 10.0

front_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: Wheel_RHS_Front_Joint
  pid:
    p: 100.0
    i: 0.1
    d: 10.0

rear_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: Wheel_LHS_Back_Joint
  pid:
    p: 100.0
    i: 0.1
    d: 10.0

rear_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: Wheel_RHS_Back_Joint
  pid:
    p: 100.0
    i: 0.1
    d: 10.0
